package ctscheduler;

public enum Shift {
    MONDAYLUNCH, MONDAYDINNER, TUESDAYLUNCH, TUESDAYDINNER, WEDNESDAYLUNCH, WEDNESDAYDINNER,
    THURSDAYLUNCH, THURSDAYDINNER, FRIDAYLUNCH, FRIDAYDINNER, SATURDAYLUNCH, SATURDAYDINNER,
    SUNDAYLUNCH, SUNDAYDINNER
}
